import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

public class GUIFrame extends javax.swing.JFrame {

    private static final String host = "jdbc:derby://localhost:1527/FlightSchedulerDBJamesjjb6295";
    private static final String user = "java";
    private static final String password = "java";
    private static ArrayList names = new ArrayList();
    static ArrayList flights = new ArrayList();
    static ArrayList dates = new ArrayList();
    private static ArrayList bookings = new ArrayList();
    private static ArrayList waitlist = new ArrayList();
    private String custName;
    private String customer;
    private String flight;
    private String date;
    private int oldSize;
    private int oldSize1;
    private int newSize;
    private int newSize1;
    private int oldSizeWaitlist;
    private int newSizeWaitlist;
    private String flightStatus;
    private String waitlistStatus;
    private int flightSeats;
    private String customerStatus;
    private String rebook;

    /**
     * Creates new form GUIFrame
     */
    public GUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AddCustomerTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CustomerName = new javax.swing.JTextField();
        AddCustomerButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FlightName = new javax.swing.JTextField();
        FlightSize = new javax.swing.JTextField();
        AddFlightButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        DateString = new javax.swing.JTextField();
        AddDateButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CustomerBooking = new javax.swing.JComboBox<>();
        DateBooking = new javax.swing.JComboBox<>();
        FlightBooking = new javax.swing.JComboBox<>();
        BookCustomerButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CustomerCancelBooking = new javax.swing.JComboBox<>();
        DateCancelBooking = new javax.swing.JComboBox<>();
        CancelBookingButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        FlightDropFlight = new javax.swing.JComboBox<>();
        DropFlightButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FlightStatusFlight = new javax.swing.JComboBox<>();
        DateStatusFlight = new javax.swing.JComboBox<>();
        CheckStatusFlight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        DateStatusWaitlist = new javax.swing.JComboBox<>();
        CheckStatusWaitlist = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        NameStatusCustomer = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        CheckStatusCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Scheduler");

        Title.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Title.setText("Flight Scheduler");

        jLabel2.setText("Customer Name:");

        CustomerName.setColumns(20);

        AddCustomerButton.setText("Add Customer");
        AddCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Flight Name:");

        jLabel11.setText("Number of Seats:");

        AddFlightButton.setText("Add Flight");
        AddFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Date (YYYY-MM-DD):");

        AddDateButton.setText("Add Date");
        AddDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddCustomerTabLayout = new javax.swing.GroupLayout(AddCustomerTab);
        AddCustomerTab.setLayout(AddCustomerTabLayout);
        AddCustomerTabLayout.setHorizontalGroup(
            AddCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCustomerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AddCustomerTabLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(AddCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(DateString)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddCustomerTabLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddCustomerTabLayout.createSequentialGroup()
                                .addComponent(FlightName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(FlightSize, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddFlightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddCustomerTabLayout.createSequentialGroup()
                                .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddCustomerButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddCustomerTabLayout.setVerticalGroup(
            AddCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCustomerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddCustomerButton))
                .addGap(18, 18, 18)
                .addGroup(AddCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(FlightName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(FlightSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFlightButton))
                .addGap(18, 18, 18)
                .addGroup(AddCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(DateString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Add", AddCustomerTab);

        jLabel1.setText("Customer:");

        jLabel3.setText("Flight:");

        jLabel4.setText("Date:");

        CustomerBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(names)));

        DateBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(dates)));

        FlightBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(flights)));

        BookCustomerButton.setText("Book");
        BookCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BookCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustomerBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FlightBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CustomerBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FlightBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BookCustomerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Booking", jPanel2);

        jLabel14.setText("Customer:");

        jLabel15.setText("Date:");

        CustomerCancelBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(names)));

        DateCancelBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(dates)));

        CancelBookingButton.setText("Cancel Booking");
        CancelBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBookingButtonActionPerformed(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CancelBookingButton)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomerCancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateCancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CustomerCancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(DateCancelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelBookingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(10, 10, 10)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Cancel Booking", jPanel5);

        jLabel19.setText("Flight:");

        FlightDropFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(flights)));

        DropFlightButton.setText("Drop Flight");
        DropFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropFlightButtonActionPerformed(evt);
            }
        });

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DropFlightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(FlightDropFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 196, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(FlightDropFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(DropFlightButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Drop Flight", jPanel6);

        jLabel6.setText("Flight:");

        jLabel7.setText("Date:");

        FlightStatusFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(flights)));

        DateStatusFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(dates)));

        CheckStatusFlight.setText("Check Status");
        CheckStatusFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckStatusFlightActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 203, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckStatusFlight)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateStatusFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(FlightStatusFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightStatusFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateStatusFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckStatusFlight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Status - Flight", jPanel3);

        jLabel9.setText("Date:");

        DateStatusWaitlist.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(dates)));

        CheckStatusWaitlist.setText("Check Status");
        CheckStatusWaitlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckStatusWaitlistActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);
        jTextArea2.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CheckStatusWaitlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(DateStatusWaitlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(DateStatusWaitlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckStatusWaitlist)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Status - Waitlist", jPanel4);

        jLabel13.setText("Customer:");

        NameStatusCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(names)));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        CheckStatusCustomer.setText("Check Status");
        CheckStatusCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckStatusCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(NameStatusCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CheckStatusCustomer)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(NameStatusCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckStatusCustomer))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Status - Customer", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setCustomer(String customer){
        this.customer = customer;
    }
    
    public String getCustomer(){
        return customer;
    }
    
    public void setFlight(String flight){
        this.flight = flight;
    }
    
    public String getFlight(){
        return flight;
    }
    
    public void setDate(String date){
        this.date = date;
    }
    
    public String getDate(){
        return date;
    } 
    
    private void AddCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerButtonActionPerformed
        AddCustomer add = new AddCustomer();
        setCustomer(CustomerName.getText());
        oldSize = names.size();
        try {
            AddCustomer.AddCustomer(getCustomer());
            newSize = names.size();
            if (oldSize < newSize){
                jLabel5.setText(getCustomer() + " was added to the database.");
            }
            else if (oldSize == newSize){
                jLabel5.setText(getCustomer() + " is already in the database.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        CustomerBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(names)));
        CustomerCancelBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(names)));
        
    }//GEN-LAST:event_AddCustomerButtonActionPerformed

    private void BookCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookCustomerButtonActionPerformed
        oldSize = bookings.size();
        oldSizeWaitlist = waitlist.size();
        BookingCustomer book = new BookingCustomer();
        setCustomer((String) CustomerBooking.getSelectedItem());
        setFlight((String) FlightBooking.getSelectedItem());
        setDate((String) DateBooking.getSelectedItem());
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        try{
            BookingCustomer.BookingCustomer(getCustomer(), getFlight(), getDate(), currentTimestamp);
            newSize = bookings.size();
            newSizeWaitlist = waitlist.size();
            if (oldSize < newSize){
                jLabel8.setText(getCustomer() + " was booked on flight " + getFlight() + " on " + getDate() + ".");
            }
            else if (oldSize == newSize){
                if (oldSizeWaitlist < newSizeWaitlist){
                    jLabel8.setText(getCustomer() + " was added to the waitlist for flight " + getFlight() + " on " + getDate() + ".");
                }
                else if (oldSizeWaitlist == newSizeWaitlist){
                    jLabel8.setText(getFlight() + getCustomer() + " is already booked on flight "  + getFlight() + " on " + getDate() + ".");
                }
            }
        }
        catch (SQLException ex){
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BookCustomerButtonActionPerformed

    private void CheckStatusFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckStatusFlightActionPerformed
        CheckFlightStatus status = new CheckFlightStatus();
        setFlight((String) FlightStatusFlight.getSelectedItem());
        setDate((String) DateStatusFlight.getSelectedItem());
        try {
            flightStatus = CheckFlightStatus.CheckFlightStatus(getFlight(), getDate());
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea1.setText(flightStatus);
    }//GEN-LAST:event_CheckStatusFlightActionPerformed

    private void CheckStatusWaitlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckStatusWaitlistActionPerformed
        CheckWaitlistStatus status = new CheckWaitlistStatus();
        setDate((String) DateStatusFlight.getSelectedItem());
        try {
            waitlistStatus = CheckWaitlistStatus.CheckWaitlistStatus(getDate());
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea2.setText(waitlistStatus);
    }//GEN-LAST:event_CheckStatusWaitlistActionPerformed

    private void AddFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightButtonActionPerformed
        AddFlight add = new AddFlight();
        try{
            flightSeats = Integer.parseInt(FlightSize.getText());
        }
        catch (NumberFormatException ex){
            jLabel5.setText("Please enter an integer for the number of seats on the flight.");
            return;
        }
        setFlight(FlightName.getText());
        oldSize = flights.size();
        try {
            AddFlight.AddFlight(getFlight(), flightSeats);
            newSize = flights.size();
            if (oldSize < newSize){
                jLabel5.setText(getFlight() + " was added to the database.");
        }
            else if (oldSize == newSize){
                jLabel5.setText(getFlight() + " is already in the database.");
        }
        }
        catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        FlightBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(flights)));        
        FlightStatusFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(flights)));
        FlightDropFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(flights)));
    }//GEN-LAST:event_AddFlightButtonActionPerformed

    private void AddDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDateButtonActionPerformed
        AddDate add = new AddDate();
        setDate(DateString.getText());
        try{
            Date day = Date.valueOf(getDate());
        }
        catch (IllegalArgumentException ex){
            jLabel5.setText("Please enter a date in the correct format.");
        }
        oldSize = dates.size();
        try{
            AddDate.AddDate(getDate());
            newSize = dates.size();
            if (oldSize < newSize){
                jLabel5.setText(getDate() + " was added to the database.");
            }
            else if (oldSize == newSize){
                jLabel5.setText(getDate() + " is already in the database.");
            }
        }
        catch (SQLException ex){
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        DateBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(dates)));
        DateStatusFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(dates)));
        DateStatusWaitlist.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(dates)));
        DateCancelBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(dates)));
    }//GEN-LAST:event_AddDateButtonActionPerformed

    private void CheckStatusCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckStatusCustomerActionPerformed
        CheckCustomerStatus status = new CheckCustomerStatus();
        setCustomer((String) NameStatusCustomer.getSelectedItem());
        try {
            customerStatus = CheckCustomerStatus.CheckCustomerStatus(getCustomer());
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea3.setText(customerStatus);
    }//GEN-LAST:event_CheckStatusCustomerActionPerformed

    private void CancelBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBookingButtonActionPerformed
        CancelBooking cancel = new CancelBooking();
        CheckFlightStatus status = new CheckFlightStatus();
        setCustomer((String) CustomerCancelBooking.getSelectedItem());
        setDate((String) DateCancelBooking.getSelectedItem());
        oldSize = bookings.size();
        oldSize1 = waitlist.size();
        try {
            setFlight(CancelBooking.CancelBooking(getCustomer(), getDate()));
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        newSize = bookings.size();
        newSize1 = waitlist.size();
        try {
            flightStatus = CheckFlightStatus.CheckFlightStatus(getFlight(), getDate());
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (oldSize == newSize){
            if (oldSize1 == newSize1){
                jLabel18.setText(getCustomer() + " was not booked or on the waitlist for any flight on " + getDate() + ".");
            }
            else{
                jLabel18.setText("The booking for " + getCustomer() + " was cancelled. Here are the updated bookings.");
                jTextArea4.setText(flightStatus);
            }
        }
        else{
            jLabel18.setText("The booking for " + getCustomer() + " was cancelled. Here are the updated bookings.");
            jTextArea4.setText(flightStatus);
        }
    }//GEN-LAST:event_CancelBookingButtonActionPerformed

    private void DropFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropFlightButtonActionPerformed
        DropFlight drop = new DropFlight();
        setFlight((String) FlightDropFlight.getSelectedItem());
        oldSize = flights.size();
        try {
            rebook = DropFlight.DropFlight(getFlight());
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        newSize = flights.size();
        if (newSize < oldSize){
            jLabel22.setText("Flight " + getFlight() + " was removed from the database.");
            jTextArea5.setText(rebook);
        }
        FlightBooking.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(flights)));
        FlightStatusFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(flights)));
        FlightDropFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new Vector<String>(flights)));
    }//GEN-LAST:event_DropFlightButtonActionPerformed
    
    private static Connection getDBConnection() {
        Connection con = null;
        try {
            con = DriverManager.getConnection(host, user, password);
            return con;
        } catch (SQLException err) {
            System.out.println(err.getMessage());
        }
        return con;
    }

    /**
     *
     * @return @throws SQLException
     */
    public static ArrayList getAllName() throws SQLException {
        names.removeAll(names);
        Connection con = getDBConnection();
        Statement stmt;
        stmt = con.createStatement();
        String sql = "Select Name from Customer";
        ResultSet rst;
        rst = stmt.executeQuery(sql);
        while (rst.next()) {
            String name = rst.getString("name");
            names.add(name);
        }       
        return names;
    }

    public static ArrayList getAllFlight() throws SQLException {
        flights.removeAll(flights);
        Connection con = getDBConnection();
        Statement stmt;
        stmt = con.createStatement();
        String sql = "SELECT Name From Flight";
        ResultSet rst;
        rst = stmt.executeQuery(sql);
        while (rst.next()) {
            String flight = rst.getString("name");
            flights.add(flight);
        }
        return flights;
    }

    public static ArrayList getAllDate() throws SQLException {
        dates.removeAll(dates);
        Connection con = getDBConnection();
        Statement stmt;
        stmt = con.createStatement();
        String sql = "SELECT Date from Day";
        ResultSet rst;
        rst = stmt.executeQuery(sql);
        while (rst.next()) {
            String date = rst.getString("date");
            dates.add(date);
        }
        return dates;
    }
    
    public static ArrayList getAllBookings() throws SQLException{
        bookings.removeAll(bookings);
        Connection con = getDBConnection();
        Statement stmt;
        stmt = con.createStatement();
        String sql = "SELECT Customer from Bookings";
        ResultSet rst;
        rst = stmt.executeQuery(sql);
        while (rst.next()){
            String booking = rst.getString("customer");
            bookings.add(booking);
        }
        return bookings;
    }
    
    public static ArrayList getAllWaitlist() throws SQLException{
        waitlist.removeAll(waitlist);
        Connection con = getDBConnection();
        Statement stmt;
        stmt = con.createStatement();
        String sql = "SELECT Customer from Waitlist";
        ResultSet rst;
        rst = stmt.executeQuery(sql);
        while (rst.next()){
            String booking = rst.getString("customer");
            waitlist.add(booking);
        }
        return waitlist;        
    }

    /**
     * @param args the command line arguments
     * @throws java.sql.SQLException
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        getAllName();
        getAllFlight();
        getAllDate();
        getAllBookings();
        getAllWaitlist();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomerButton;
    private javax.swing.JPanel AddCustomerTab;
    private javax.swing.JButton AddDateButton;
    private javax.swing.JButton AddFlightButton;
    private javax.swing.JButton BookCustomerButton;
    private javax.swing.JButton CancelBookingButton;
    private javax.swing.JButton CheckStatusCustomer;
    private javax.swing.JButton CheckStatusFlight;
    private javax.swing.JButton CheckStatusWaitlist;
    private javax.swing.JComboBox<String> CustomerBooking;
    private javax.swing.JComboBox<String> CustomerCancelBooking;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JComboBox<String> DateBooking;
    private javax.swing.JComboBox<String> DateCancelBooking;
    private javax.swing.JComboBox<String> DateStatusFlight;
    private javax.swing.JComboBox<String> DateStatusWaitlist;
    private javax.swing.JTextField DateString;
    private javax.swing.JButton DropFlightButton;
    private javax.swing.JComboBox<String> FlightBooking;
    private javax.swing.JComboBox<String> FlightDropFlight;
    private javax.swing.JTextField FlightName;
    private javax.swing.JTextField FlightSize;
    private javax.swing.JComboBox<String> FlightStatusFlight;
    private javax.swing.JComboBox<String> NameStatusCustomer;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}